language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
install:
  - pip install coveralls 
script:
  - python setup.py nosetests --with-coverage --cover-package=presser
after_success:
    - coveralls